version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: "db"
    env_file:
      - ./server/postgres.env
    ports:
      - "5432:5432"
    networks:
      - backend
  app:
    container_name: "app"
    build: ./server
    restart: always
    environment:
      CONFIG_PATH: "/prod.yaml"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend
  frontend:
    build: ./ggteam
    container_name: vite
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge
